. /usr/lib/ybs/funcs

schemas_file="/usr/share/softwarecenter/ypk-thumbnailer.schemas"
mime_file="/usr/share/softwarecenter/ypk-package.xml"

post_install() {
    gnome2_install_schema "$schemas_file"
    gnome2_install_mine   "$mime_file"
}

pre_remove() {
    gnome2_uninstall_schema "$schemas_file"
    gnome2_uninstall_mine   "$mime_file"
}

post_remove() {
    true
}

post_upgrade() {
    post_install
}

post_downgrade() {
    post_install
}

